### ISSUE TITLE
Quesiton: Configuration parameters - exceptions: false

### ISSUE THREAD

**Issue by thim81** [csarrazi/CsaGuzzleBundle#112]
Hi Csarrazi

Question on the config options:

Is it possible to set in the client config that exceptions are ignored?

In the Guzzle documentation, I found the following:

````
$client = new Client([
    'base_uri' => 'http://authen.sso.dev',
    'exceptions' => false,
]);
````

Something like this, I tried this but it's not working
```
csa_guzzle:
    profiler: %kernel.debug%
    clients:
        api_client:
            config:
                base_uri: %find_a_cordoval_api_url%
exceptions: false
                auth: [%find_a_cordoval_api_user%, %find_a_cordoval_api_pass%, 'basic']
                defaults:
                    headers:
                        Accept: application/json
            middleware: []
            class: GuzzleHttp\Client

````

**Comment by csarrazi** [comment]
Is your indentation is wrong. Regardless, you should use the `http_errors` option, set to `false`.

See http://guzzle.readthedocs.org/en/latest/request-options.html#http-errors 

```yml
csa_guzzle:
    profiler: %kernel.debug%
    clients:
        api_client:
            config:
                base_uri: %find_a_cordoval_api_url%
                auth: [%find_a_cordoval_api_user%, %find_a_cordoval_api_pass%, 'basic']
                defaults:
                    headers:
                        Accept: application/json
                        http_errors: false
            middleware: []
            class: GuzzleHttp\Client
```
