### ISSUE TITLE
Enable a subscriber for only one client

### ISSUE THREAD

**Issue by walouster** [csarrazi/CsaGuzzleBundle#117]
With the following config, all subscribers (logger, stopwatch... and also my_custom_subscriber) are injected to no_subscriber_client, while neither is expected.

As all subscribers are enabled for all client, this is the only way to achieve this.

``` yaml
no_subscriber_client:
    class: %my_client_class%
    subscribers:
        my_custom_subscriber: false

my_second_client:
    class: %my_client_class%
    subscribers:
        my_custom_subscriber: true
```

**Comment by csarrazi** [comment]
This cannot be fixed easily. The default behavior is that if you have no enabled subscriber, all subscribers will be used. As we don't have access to the complete list of subscribers outside of the compiler pass, this means that we need to handle this in the compiler pass, instead of the DI extension. Thus, we may need to use a parameter in order to pass this information from the config. I will try to check if I can fix this next week.

**Comment by csarrazi** [comment]
Support for disabling explicitely a middleware / subscriber was removed for the 2.x branch. This will be re-implemented for release 2.1, with a much better implementation.

**Comment by csarrazi** [comment]
What I'm thinking about is basically prefixing the middleware with `!`, to disable it for the client.

I think that notation is both clear and concise.

E.g.

```yml
csa_guzzle:
    clients:
        my_client:
            middleware: ["!my_auth"]
        my_other_client:
            middleware: ["my_auth"]
```

What do you think about this?
