### ISSUE TITLE
2.0.4 is broken when using Symfony 2.7

### ISSUE THREAD

**Issue by fbourigault** [csarrazi/CsaGuzzleBundle#118]
When Symfony 2.7 is used, the PHP dump container is invalid. This happens when no handler waas provided to any client. Using Symfony 2.8.1, the container is valid (maybe 2.8.0 is working too, but I haven't tested it).

I originaly reported the issue in https://github.com/symfony/symfony/issues/17353.

Probably the minimum version of `symfony/dependency-injection` should be `^2.8|^3.0`

**Comment by csarrazi** [comment]
Can you show your configuration?

Normally, this should work correctly using Symfony 2.7 (which we have been using on quite a few projects).

**Comment by fbourigault** [comment]
I'm using `$container->preprendExtensionConfig`:
```php
+        $container->prependExtensionConfig('csa_guzzle', [
+            'clients' => [
+                'client1' => [
+                    'config' => [
+                        'base_uri' => 'base_uri',
+                        'headers' => [
+                            'Authorization' => 'Bearer token',
+                            'Content-Type' => 'content_type_client_1'
+                        ]
+                    ]
+                ],
+                'client2' => [
+                    'config' => [
+                        'base_uri' => 'base_uri',
+                        'headers' => [
+                            'Authorization: Bearer token',
+                            'Content-Type' => 'content_type_client2'
+                        ]
+                    ]
+                ]
+            ]
+        ]);
```

From `app/console debug:config CsaGuzzleBundle`, i get:
```yml
csa_guzzle:
    clients:
        client1: { config: { base_uri: 'base_uri', headers: { Authorization: 'Bearer token', Content-Type: content_type_client1 } }, class: GuzzleHttp\Client, lazy: false, middleware: {  }, alias: null }
        client2: { config: { base_uri: 'base_uri', headers: { 0: 'Authorization: Bearer token', Content-Type: content_type_client2 } }, class: GuzzleHttp\Client, lazy: false, middleware: {  }, alias: null }
    profiler:
        enabled: true
        max_body_size: 65536
    logger:
        enabled: true
        service: null
        format: '{hostname} {req_header_User-Agent} - [{date_common_log}] "{method} {target} HTTP/{version}" {code} {res_header_Content-Length}'
        level: debug
    cache:
        enabled: false
        adapter: null
    mock:
        enabled: false
        mode: replay
```
