### ISSUE TITLE
[Doc] The configuration reference seems not up to date

### ISSUE THREAD

**Issue by salahm** [csarrazi/CsaGuzzleBundle#13]
Tree builder for `cache`node have been recently changed, and the doc was not updated.
The old one :
```YAML
cache:
        enabled:              false
        type:                 doctrine
        service:              ~
```
The new one :
```YAML
cache:
        enabled:              false
        service:              ~
        adapter: 
            type:                 doctrine
```
