### ISSUE TITLE
Custom service with construct parameters

### ISSUE THREAD

**Issue by tlenclos** [csarrazi/CsaGuzzleBundle#132]
Hi !
When trying to define a custom service with symfony I'm facing a weird error in the MiddlewarePass.

```
PHP Warning:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: Illegal string offset 'handler'' in /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php:124
Stack trace:
#0 /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php(124): Symfony\Component\Debug\ErrorHandler->handleError(2, 'Illegal string ...', '/vagrant/vendor...', 124, Array)
#1 /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php(33): Csa\Bundle\GuzzleBundle\DependencyInjection\CompilerPass\MiddlewarePass->registerMiddleware(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Array)
#2 /vagrant/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(107): Csa\Bundle\GuzzleBundle\DependencyInjection\CompilerPass\MiddlewarePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /vagrant/vendor/symfony/symfony/src/Symfony/Component/Depen in /vagrant/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php on line 124
```

My service definition looks like this
```
custom_client:
    class: Bundle\CustomClient
    factory: [Bundle\CustomClient, createClient1]
    arguments:
      - %api_host%
      - %token1%
      - %token2%
    tags:
      - { name: csa_guzzle.client }
```

I'm trying to migrate from guzzle5 to guzzle6, maybe I missed something in the doc but I can't see how to create a custom client with arguments here https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/doc/clients.md#registering-your-own-service.

Do you have any ideas ?
