### ISSUE TITLE
Disable cert verification

### ISSUE THREAD

**Issue by nurikabe** [csarrazi/CsaGuzzleBundle#159]
Should I be able to do something like this?:

```
csa_guzzle:
    clients:
        some_api:
            config:
                base_url: https://blahblah
                verify: false
```

If so, not having much luck for some reason.
