### ISSUE TITLE
tagged client with middleware loses debug middleware

### ISSUE THREAD

**Issue by ivoba** [csarrazi/CsaGuzzleBundle#183]
I am not sure if this is a bug, maybe you can clarify.  
I have a client service defintion that has also custom middleware:

```
  my.client:
    class: GuzzleHttp\Client
    arguments:
      -
        verify: false
        base_uri: "%my.rest.uri%"
    tags:
      - {name: "csa_guzzle.client", middleware: stopwatch history !logger custom_logger}
```

And i have to explicitly add stopwatch & history to have calls of this client in the profiler again.  
In the global config i have `profiler: true` so i would have expected that this is still true for a client that is created by tagging the service.

Or is this intended behaviour?

**Comment by csarrazi** [comment]
Hi @ivoba. This is actually the expected. Maybe the documentation should be clearer. This actually prevents a bug which occurred with version `1.x` of the bundle. If you specify a list of middleware, then the middleware were not excluded anymore. Regardless, it does not make sense to use both whitelist and blacklist in the configuration.

**Comment by csarrazi** [comment]
@ivoba By the way, if you use the configuration instead of a service definition, you should have the expected behavior (disabling or enabling of the middleware).

**Comment by ivoba** [comment]
Another strange thing is that now also the clients defined by configuration use the middleware added to the client that was defined by tag.

Imho this should not happen. One client should not be able to change another client.

What i want to achieve is to have one client that uses a custom logger and not the logger the other clients use.  
Or more common: to use different middleware per client.
Is this only possible by configuration?

I also like the posibility of using service definition here, because it makes it possible to ship the client in a bundle without having to touch the csa_guzzle configuration.

**Comment by csarrazi** [comment]
Hum, could you explain this more precisely? I am not sure that I get what you are saying.
By default, *all* middleware are injected in all clients, if you don't specify the list of middleware you want for a client.

The only two exceptions are the debug and stopwatch middleware, which are added whenever the profiler is enabled, for all clients. But as soon as you specify a single middleware in the tag (or the configuration), then it should be associated to the client. So normally, you should not middleware that you did not specify in the service definition. I will take a look at the compiler pass, to see if there's anything wrong here.

By the way, you should use either the configuration, or the service, but not both. The configuration automatically exposes a service, with a default name (`csa_guzzle.client.my_client`), or you can override the name in the configuration's `alias` key. See the [configuration reference](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/doc/configuration_reference.md)

You can actually use different middleware per client. You simply need to use the middleware key in each client's configuration:

```yaml
csa_guzzle:
    # ...
    clients:
        # Prototype
        client1:
            config:
                base_uri: http://bar.com
            middleware: [ '!logger', 'custom_logger' ]
        # Prototype
        client2:
            config:
                base_uri: http://foo.com
            middleware: [ 'logger', '!custom_logger' ]
```

The `!` special character actually disables the middleware for that specific client.

By the way, if you want to use a custom logger for a specific client, you should define another middleware (`custom_log`, for example, in which you can inject your own logger):

```xml
<container>
    <services>
        <service id="my_bundle.middleware.custom_log" class="Closure">
            <factory class="GuzzleHttp\Middleware" method="log" />
            <argument type="service" id="my_custom_logger" />
            <argument type="service" id="csa_guzzle.logger.message_formatter" />
            <argument /> <!-- Logger level -->
            <tag name="csa_guzzle.middleware" alias="custom_logger" />
        </service>
    </services>
</container>
```
