### ISSUE TITLE
Enabling logging causes empty stream.

### ISSUE THREAD

**Issue by BowlingX** [csarrazi/CsaGuzzleBundle#193]
I have the following configuration:

``` yml
csa_guzzle:
    clients:
      offers:
        class: AppBundle\Service\SomeApi
        config:
          base_uri: "%api_url%"
        middleware: ['json']
    profiler: '%kernel.debug%'
    logger:
        enabled: '%kernel.debug%'
        format: debug
``` 

And the following json middleware

``` php

class DeserializedJsonStream implements StreamInterface, DeserializedStreamInterface
{
    /**
     * @var SerializerInterface
     */
    protected $serializer;

    use StreamDecoratorTrait {
        StreamDecoratorTrait::__construct as streamConstruct;
    }

    /**
     * @param StreamInterface $stream
     * @param SerializerInterface $serializer
     */
    public function __construct(StreamInterface $stream, SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
        $this->streamConstruct($stream);
    }

    public function deserialize(string $type = null)
    {
        $contents = (string)$this->getContents(); // this creates a string copy of the stream (calls copy_to_string)
        if (!$type) {
            return json_decode($contents, true);
        }
        return $this->serializer->deserialize($contents, $type, 'json');
    }
}

``` 

In connection with enabled logging, the stream object is empty. It loooks like the first read of `$message->getBody()` (and converting it to a string) will empty the stream.

See `GuzzleHttp\Psr7\str()`. If I remove the `$message->getBody()` method there, everything works fine (but logging does not work of course)

I'm not sure If this is a bug of the guzzle library or I'm just not correctly using the Middleware conversion .
