### ISSUE TITLE
Middleware blacklisting

### ISSUE THREAD

**Issue by iamluc** [csarrazi/CsaGuzzleBundle#194]
I have some troubles about middleware blacklisting. It seems it is allowed to mix blacklisting with whitelisting (https://github.com/csarrazi/CsaGuzzleBundle/blob/master/tests/DependencyInjection/CompilerPass/MiddlewarePassTest.php#L60).

IMO, it should no be the case, as blacklisting only one middleware results to no middleware at all (because of https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/DependencyInjection/CompilerPass/MiddlewarePass.php#L177)

Is this the correct behavior ?

**Comment by csarrazi** [comment]
I do agree that we should either whitelist or blacklist middleware. Want to make a small PR for that?

However, this would be a breaking change, so it should be scheduled for 3.x. I'll create a new branch for work on the current stable version, and a new branch in order to start development for 3.x.

**Comment by csarrazi** [comment]
Branch created. The `master` branch will be the branch for version 3.x, and the `2.x` branch the one for version 2.x.

**Comment by iamluc** [comment]
Thanks !
I will try to work on this on the next days

**Comment by peshi** [comment]
So this means that a config like this doesn't work for me anymore.

```
csa_guzzle:
    ....
    clients:
        some_client_without_auth:
            config:
                base_uri: "https://rest.example.com"
                ...
            middleware: ['!json_auth']
        some_client_with_auth:
            config:
                base_uri: "https://rest.example.com"
                ...
            middleware: ['json_auth']
```

**Comment by csarrazi** [comment]
This approach should normally work. What we mean by "mixing" is having both blacklisting and whitelisting in the same service definition or client configuration.

**Comment by peshi** [comment]
I see, well this was the only config I had - and it doesn't permit me to use this config.

**Comment by csarrazi** [comment]
I'll check this. Regardless, you should not use the master branch, especially since it is the development branch for 3.x and things will break very often

**Comment by peshi** [comment]
Thanks, well - people keep saying this regarding master branch. But hey.. someone has to test? :)

**Comment by csarrazi** [comment]
True! Regardless, thanks for the feedback. I'll investigate this tomorrow.

**Comment by csarrazi** [comment]
@peshi I am not able to reproduce your problem. Could you describe a bit what is your exact issue?

**Comment by peshi** [comment]
@csarrazi My issue was that I could not use the configuration pasted above. It would just tell me that I can't mix whitelisting and blacklisting. However - I solved it by not using a middleware.

Previously I used a middleware to modify a request described in previous issues: https://github.com/csarrazi/CsaGuzzleBundle/issues/129 and https://github.com/csarrazi/CsaGuzzleBundle/issues/117

But after some thinking I don't think that was the best solution for my use case.

**Comment by csarrazi** [comment]
@peshi Normally, the following configuration should work:

```yaml
csa_guzzle:
    ....
    clients:
        some_client_without_middleware:
            config:
                base_uri: "https://rest.example.com"
                ...
            middleware: ['!my_middleware']
        some_client_with_middleware:
            config:
                base_uri: "https://rest.example.com"
                ...
            middleware: ['my_middleware']
```

I'm a bit at a loss as to why this does not work, so I'll investigate this Sunday or an evening next week as I am a bit busy this week!
