### ISSUE TITLE
Example of usage needed

### ISSUE THREAD

**Issue by sergeda** [csarrazi/CsaGuzzleBundle#2]
It's not very detailed docs. Actually can't understand how to use it after install at all. Please add some more info

**Comment by micayael** [comment]
Hi.

I don't found a "Csa\Bundle\GuzzleBundle\Factory\Client" class. I found a "ClientFactory" in that namespace and actually recive a class into the constructor and documentation does not show that

<service
        id="acme.client"
        class="%acme.client.class%"
        factory-service="csa_guzzle.client_factory"
        factory-method="create">
    
    <tag name="csa_guzzle.client" />
</service>

**Comment by csarrazi** [comment]
The bunde has changed. The `Csa\Bundle\GuzzleBundle\Factory\Client` is no longer necessary and thus has been removed. This information can be found in the [upgrade documentation](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/UPGRADE-1.1.md)

**Comment by csarrazi** [comment]
You should use the `GuzzleHttp\Client` class instead.

**Comment by micayael** [comment]
Thanks por the answer but is still confusing

I am using this

  my_own_id:
      class: GuzzleHttp\Client

  api:
      class: GuzzleHttp\Client
      tags:
          - { name: csa_guzzle.subscriber, alias: acme_custom }

The request executes but I got nothing in the web profiler. Can you put a real example for de service configuration?

I have to create a suscriber for: Acme\DemoBundle\Guzzle\Subscriber\CustomSubscriber? because you said in upgrade documentation:

"You should now use the base GuzzleHttp\Client class, or your own class, extending Guzzle's class"

So I undarstand that I have to use class: GuzzleHttp\Client

**Comment by micayael** [comment]
I have this into a controller example

    $client = $this->get('api');

    $response = $client->get(
        'http://server/path',
        ['auth' => ['admin', 'admin']]
    );

    dump($response);

    dump($response->json());

I got data from the server but the icon into the web profiler said success: 0, errores: 0

**Comment by csarrazi** [comment]
Ok. I see what is wrong. Regardless, you should create the service using the ClientFactory.

```yml
my_own_id:
    class: GuzzleHttp\Client
    factory_service: csa_guzle.client_factory
    factory_method: create
```

This should solve your problem.

If you don't use the factory, then the subscribers are not attached.

Also, you could simply configure your client using the configuration:

```yml

csa_guzzle:
    profiler: true
    logger: true
    clients:
        my_client:
            config:
                base_url: https://yourdomain.tld
            subscribers:
                debug: true
                stopwatch: true
                logger: true
```
But this is only possible since v1.2.0-RC1
Using this way will automatically create a service named `csa_guzzle.client.my_client`, using the defined subscribers.
