### ISSUE TITLE
No logs in staging or prod env

### ISSUE THREAD

**Issue by orasik** [csarrazi/CsaGuzzleBundle#203]
Hi,
Logger is working fine in dev env but not in prod or staging. I thought its due to logging level differences but even after assigning debug to staging and clearing cache it didn't work.
Is there any restriction on logging to environment?

my config:

```yaml
    logger:
        enabled: true
        service: ~
        format:  '[{date_common_log}] "{method} {url}" Status [{code}] Body: [{req_body}] - Response: [{res_body}]'
        level:   debug
```

Kind Regards,
Oras

**Comment by csarrazi** [comment]
Hi Oras,

Normally, this mostly has to do with the logger that you configure. But did you add the log middleware in your configuration?

The logger is automatically added as a middleware in development (which will no longer be the case on the `master` branch, for 3.0), but that is not the case if you specify additional middleware.

**Comment by orasik** [comment]
Thanks Charles, 
I have enabled it as per docs:
```
    logger:
        enabled: true
        format:  '[{date_common_log}] "{method} {url}" Status [{code}] Body: [{req_body}] - Response: [{res_body}]'
        level:   debug
```

in client config, I added:

```
    clients:
        client_name:
            config: 
                base_uri: "https://somedomain.com"
                timeout: 10
                connect_timeout: 10
                headers:
                    Accept: application/json
                    Content-Type: application/json
            middleware: ['logger']
```

Anything I am missing?

Thanks for your help

Oras
