### ISSUE TITLE
Error specifying custom Client

### ISSUE THREAD

**Issue by TomSchillemans** [csarrazi/CsaGuzzleBundle#207]
I tried to create a custom client so I can set a header for every client created.
I am using symfony 3.3 with autowire

My config is as follows:

```yml
  HeinenoordAssuradeuren\Bundle\GeneralBundle\Guzzle\Client:
    tags:
      - { name: csa_guzzle.client }
    arguments:
      $session: "@session"
      $config:
        base_uri: "%dom_service_host%/api/"
```

and the csa config:
```yml
csa_guzzle:
  profiler: '%kernel.debug%'
  logger: true
  clients:
    services_api:
      config:
        base_uri: '%dom_service_host%/api/'
        verify: false
        exceptions: false
```

and my class:
```php
class Client extends \GuzzleHttp\Client
{
    
   public function __construct(SessionInterface $session, array $config = [])
    {
        $token = $session->get('ha-auth-token')['access_token'];
        $config['headers'] = ['Authorization' => "Bearer $token"];

        parent::__construct($config);
    }
}
```

But I get the following exception and I can't find what it is.

`Cannot use object of type Symfony\Component\DependencyInjection\Reference as array`
