### ISSUE TITLE
Redis Cache, maybe SncRedisBundle Or Doctrine Redis cache?

### ISSUE THREAD

**Issue by ajanssen** [csarrazi/CsaGuzzleBundle#29]

**Comment by csarrazi** [comment]
Please read the docs before writing issues. Using `doctrine/cache` is [fully documented here].(https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/doc/available_subscribers.md#the-cache-subscriber)

You may add any Doctrine cache implementation of your choice. You simply need to configure the bundle as follows:

```yml
# in config.yml
csa_guzzle:
    cache:
        enabled: true
        adapter:
            type: doctrine
        service: my.cache.service

# in services.yml
services:
    my.cache.service:
        class: Doctrine\Common\Cache\RedisCache
```

However, keep in mind that the bundle's configuration will change slightly for version 1.3, as you will only be able to set a cache adapter. Then, the configuration will change to:

```yml
# in config.yml
csa_guzzle:
    cache:
        enabled: true
        adapter: my.cache.adapter

# in services.yml
services:
    my.cache.adapter:
        class: Csa\Bundle\GuzzleBundle\GuzzleHttp\Cache\DoctrineAdapter
        arguments: [ @my.cache.service ]
    my.cache.service:
        class: Doctrine\Common\Cache\RedisCache
```

`my.cache.service` may also be created using `doctrine-cache-bundle`, and you can even create your own adapter by using `snc/redis-bundle` (or directly use `phpredis`), and implement `Csa\Bundle\GuzzleBundle\GuzzleHttp\Cache\StorageAdapterInterface`.
