### ISSUE TITLE
Add class parameter in client config

### ISSUE THREAD

**Issue by mRoca** [csarrazi/CsaGuzzleBundle#36]
In order to use custom client classes, we actually need to declare a tagged service and inject the config array as argument.

A `class` config option should be a good functionality, for example : 

```
csa_guzzle:
    profiler: %kernel.debug%
    logger: true
    clients:
        my_api:
            class: MyBundle\MyClient
            config:
                base_url: %api_url%
                defaults:
                    headers:
                        Accept: application/ld+json
```
