### ISSUE TITLE
Supplying auth to the service.

### ISSUE THREAD

**Issue by emil-nasso** [csarrazi/CsaGuzzleBundle#40]
Previously i had a service that looked like this:

```yml
  guzzle.example:
    class: GuzzleHttp\Client
    factory: ["@csa_guzzle.client_factory", create]
    arguments:
      options:
        "base_url" : "http://127.0.0.1"
        defaults:
          "auth" : [ "user", "password" ]
```

That worked great.

I upgraded symfony/this bundle and started getting deprecation notices that the factory was going away.

I tried to rewrite it like this, according to the documentation:

```yml
csa_guzzle:
    profiler: %kernel.debug%
    clients:
        example:
            config:
                base_url: "http://127.0.0.1"
                defaults:
                    auth : [ "user", "password" ]
```

In my `config.yml` instead of the `services.yml`

The problem is that this doesnt seem to use the auth-information. How to i supply the auth-information (basic http authentication) this way?

**Comment by csarrazi** [comment]
Hi Emil, and thank for the feedback. Normally, that should be working, as the configuration simply dumps the content of the config array in the client's configuration.

Could you dump what you have in `app/cache/dev/appDevDebugProjectContainer`, in the `getCsaGuzzle_Client_ExampleService()` method? (Replace `Example` by the camelcased version of your client's name)

**Comment by emil-nasso** [comment]
Hmm. It must have been a caching issue... I tried some other stuff after writing this, and reset everything to the example above and cleared cache. Now everything seems to be working. :)

Here is the requested method for future reference:

```php
protected function getCsaGuzzle_Client_ExampleService()
    {
        $this->services['csa_guzzle.client.example'] = $instance = new \GuzzleHttp\Client(array('base_url' => 'http://127.0.0.1', 'defaults' => array('auth' => array(0 => 'username', 1 => 'password'))));

        call_user_func(array(new \Csa\Bundle\GuzzleBundle\DependencyInjection\Configurator\ClientConfigurator(array(0 => $this->get('csa_guzzle.subscriber.stopwatch'), 1 => $this->get('csa_guzzle.subscriber.debug')), NULL), 'configure'), $instance);

        return $instance;
    }

```

Thanks for the fast response, though. :) :+1:

**Comment by csarrazi** [comment]
Glad to hear that clearing the cache solved your issue! :)

You're welcome!

**Comment by cordoval** [comment]
I got the same problem and it is not cache related

**Comment by csarrazi** [comment]
Which version are you using? Can you open a new ticket, @cordoval? :)

**Comment by cordoval** [comment]
I found the solution by going into the code :+1: 

here is the answer:

```yaml
csa_guzzle:
    profiler: %kernel.debug%
    clients:
        find_a_cordoval_client:
            config:
                base_uri: %find_a_cordoval_api_url%
                auth: [%find_a_cordoval_api_user%, %find_a_cordoval_api_pass%, 'basic']
                defaults:
                    headers:
                        Accept: application/json
            middleware: []
            class: GuzzleHttp\Client
```
