### ISSUE TITLE
Custom client

### ISSUE THREAD

**Issue by theofidry** [csarrazi/CsaGuzzleBundle#43]
I'm declaring my client as a service since I wish to inject some dependencies in it. My client declaration is:

```yaml
services:
    api.client:
        class: FrontBundle\Client\ApiClient
        arguments:
            - @router
            - http://localhost/api
        tags: [ { name: csa_guzzle.client } ]
```

However this throw the following error:

    PHP Fatal error:  Cannot use object of type Symfony\Component\DependencyInjection\Reference as array in /path/to/myProject/vendor/csa/guzzle-bundle/src/DependencyInjection/CompilerPass/MiddlewarePass.php on line 106

Any idea?

Edit:
* Using Symfony2.7 and the version `dev-master` of the bundle

**Comment by csarrazi** [comment]
Your problem comes from the fact that you are extending the client in a wrong way. FYI, the only way to inject middleware in the Guzzle client is to inject the middleware in a handler, which is then passed in the client's options array. See http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html

So instead of using constructor injection, you should rather use setter injection, by creating a `setRouter()` method, and using `call` to add a method call after instanciation. For the URI, you should use Guzzle's recommended method, which is to pass it in the configuration array.

E.g:

```yml
services:
    api.client:
        class: FrontBundle\Client\ApiClient
        arguments:
            - { uri: "http://localhost/api" }
        calls:
            - { method: setRouter, [ "@router" ]}
        tags: [ { name: csa_guzzle.client } ]
```

By the way, unless you explicitely want to use Guzzle 6.0, you may want to stick with a stable version (`^1.3`) of the bundle, instead of `dev-master`, which is not production-ready yet (there's even a warning at the top of the bundle's documentation). :)

This issue could be fixed by using reflexion, and introspect the class' constructor to detect whether there is an options argument in the client, but there will be other edge cases, so I don't think it's worth all the hastle. I'll add documentation to explain how to correctly extend the Guzzle client. :)

**Comment by csarrazi** [comment]
@theofidry Did you try anything?

**Comment by theofidry** [comment]
I'm currently trying, I get the following error:

    Warning: strpos() expects parameter 1 to be string, array given
500 Internal Server Error - ContextErrorException

```
in vendor/guzzle/guzzle/src/Guzzle/Parser/UriTemplate/UriTemplate.php at line 41
39.    public function expand($template, array $variables)
40.    {
41.        if ($this->regex == self::DEFAULT_PATTERN && false === strpos($template, '{')) {
42.            return $template;
43.        }
```

Btw just a minor erorr in the service declaration:

```yaml
services:
    api.client:
        class: FrontBundle\Client\ApiClient
        arguments:
            - { uri: "http://localhost/api" }
        calls:
            - [ setRouter, [ "@router" ] ]
        tags: [ { name: csa_guzzle.client } ]
```

or 

```yaml
services:
    api.client:
        class: FrontBundle\Client\ApiClient
        arguments:
            - { uri: "http://localhost/api" }
        calls:
            - { method: setRouter, arguments: [ "@router" ] }
        tags: [ { name: csa_guzzle.client } ]
```
But that's not the issue

**Comment by csarrazi** [comment]
My bad. Change the config to this:

```yml
services:
    api.client:
        class: FrontBundle\Client\ApiClient
        arguments:
            - { uri: "http://localhost/api" }
        calls:
            - [ setRouter, [ "@router" ]]
        tags: [ { name: csa_guzzle.client } ]
```

It should work better.
