### ISSUE TITLE
Add documentation for symfony service injection in the guzzle client

### ISSUE THREAD

**Issue by csarrazi** [csarrazi/CsaGuzzleBundle#52]
With release `1.3.2`, symfony services can now be injected in a client's configuration.

This should be documented in the `1.3` branch.

**Comment by rvanlaak** [comment]
Another use case to document; changing the client's class, and how to autowire that to another own service definition.

We use the bundle as "a factory" for our own autowireable class:

```php
<?php

namespace Acme\Infra\Shopping;

class Client extends \GuzzleHttp\Client
{
}
```
```yml

csa_guzzle:
    clients:
        shopping:
            class: 'Acme\Infra\Shopping\Client'
            config:
                base_uri: '%shopping.base_uri%'
``` 

... and we want to autowire that class in our own service definition:

```yml
services:
    Acme\Application\Shopping\Cart:
        arguments: ['@Acme\Infra\Shopping\Client']   
``` 

For controller action argument autowiring this works perfectly, but for resolving service arguments on container compilation this unfortunately gives a "service not found" exception because the bundle registers the client to the container after it resolves the rest of the services.

Probably the solution is somewhere in compilation priorities. It would be great to have documentation on this, as the above allows everyone to make use of all the great middleware the bundle can register with the clients.
