### ISSUE TITLE
ContextErrorException in GuzzleCollector.php line 65: Notice: Undefined index: response

### ISSUE THREAD

**Issue by bgatellier** [csarrazi/CsaGuzzleBundle#84]
Hello,

I just have updated the bundle today using the @stable branch, and I now encountering the following error:
```
ContextErrorException in GuzzleCollector.php line 65: Notice: Undefined index: response
```
I was still using the @stable branch a couple of days ago, and everything was fine.

For the record, here are my configurations when using the bundle:
config.yml:
```
csa_guzzle:
    clients:
        my_api:
            config:
                base_url: %api.url%
                defaults:
                    headers:
                        Accept: %api.headers.accept%
```

services.yml:
```
services:
    bundle_api.api_client:
        class: Api\ApiBundle\Service\ApiClient
        arguments:
            - "@request_stack"
            - "@csa_guzzle.client.my_api"
            - "%locale.default%"
```
ApiClient.php:
```
use Csa\Bundle\GuzzleBundle\HttpFoundation\StreamResponse;
use GuzzleHttp\Client as GuzzleClient;
use Symfony\Component\HttpFoundation\RequestStack;

class ApiClient
{
    private $client;
    private $currentLocale;

    /**
     * Constructor
     * @param string $localeDefault 
     */
    public function __construct(RequestStack $requestStack, GuzzleClient $client, $localeDefault)
    {
        $this->client = $client;
        $this->currentLocale = (!$requestStack->getCurrentRequest()) ? $localeDefault : $requestStack->getCurrentRequest()->getLocale();
    }
```

Anyway, thank you for your bundle and the efforts you provide to keep it up-to-date ;-)
