### ISSUE TITLE
Question: Does your client config support auth for username and password?

### ISSUE THREAD

**Issue by thim81** [csarrazi/CsaGuzzleBundle#94]
Does the configuration support auth settings, something like this?
```
csa_guzzle:
    clients:
        github_api:
            config:
                base_url: https://api.github.com
                auth:
                    username: login
                    password: xxxxx
                defaults:
                    headers:
                        Accept: application/vnd.github.v3+json
```

**Comment by csarrazi** [comment]
Yes, it should. If you are using Http Basic, the configuration should be like this.

For the Github API, the configuration should be something like:

```yml
csa_guzzle:
    clients:
        github_api:
            config:
                base_url: https://api.github.com
                defaults:
                    headers:
                        Authorization: token mygithubtoken1234567890
                        Accept: application/vnd.github.v3+json
```

For http-basic, you simply need to transpose your guzzle config array in the yaml configuration.

**Comment by csarrazi** [comment]
Basically, the `config` key is used to inject your Guzzle client's config. This config is **exactly** what is mentioned in Guzzle's documentation, as the client's constructor argument.

**Comment by thim81** [comment]
Hi Csarrazi,

Thanks for the quick and clear explanation.

Guzzle mentions the usage like:
```
$client->request('GET', '/get', ['auth' => ['username', 'password']]);
````

So looking at your example and my example, this could work:

````
csa_guzzle:
    clients:
        my_api:
            config:
                base_url: https://api.service.com
                defaults:
                    headers:
                        Authorization: login mypassword
                        Accept: application/json
````

**Comment by csarrazi** [comment]
Nope. It would be something like

```yml
csa_guzzle:
    clients:
        my_api:
            config:
                base_uri: https://api.service.com
                auth: [login, mypassword]
                headers:
                    Accept: application/json
```
