### ISSUE TITLE
GuzzleCollector undefined index `response`

### ISSUE THREAD

**Issue by wizbit** [csarrazi/CsaGuzzleBundle#98]
When running a basic setup I get the following exception:
> ContextErrorException in GuzzleCollector.php line 65:
> Notice: Undefined index: response

My config is 
```yaml
csa_guzzle:
  profiler:
    enabled: %kernel.debug%
  logger:
    enabled: true
  clients:
    github:
      config:
        base_uri: http://github.com
```
My controller is simple:
```php
    public function indexAction()
    {
        $response = $this->get('csa_guzzle.client.github')->get('/');
        return new Response($response->getBody()->getContents());
   }
```
This is using "csa/guzzle-bundle": "^2.0"
